services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
  matrix:
    - VFBSUB=local OWLURL=http://www.virtualflybrain.org/owl/vfb.owl
    - VFBSUB=Current OWLURL=https://github.com/VirtualFlyBrain/VFB_owl/blob/Current/src/owl/vfb.owl.gz?raw=true
    - VFBSUB= OWLURL=https://github.com/VirtualFlyBrain/VFB_owl/blob/dev/src/owl/vfb.owl.gz?raw=true
    - OWLURL=https://github.com/VirtualFlyBrain/VFB_owl/blob/scala-dev/src/owl/vfb.owl.gz?raw=true

script:
  - echo -e "travis_fold:start:Geppetto-Config"
  - export REPO=$(echo ${TRAVIS_REPO_SLUG} | awk '{gsub(/\./,"_",$0);print tolower($0)}')
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - sed -i "s|http://www.virtualflybrain.org/owl/vfb.owl|${OWLURL}|g" application.conf
  - docker build -t test-image:test .
  - docker run -d --name test -p 127.0.0.1:80:8080 test-image:test
  - sleep 2m
  - docker logs test
  - curl -sSf http://127.0.0.1/kbs/vfb
after_success:
  - cd $TRAVIS_BUILD_DIR
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - |
    if [ "$VFBSUB" != "local" ]; then
      docker push $REPO:$TAG-$VFBSUB
    else
      docker push $REPO:$TAG
    fi
    
